### PR TITLE
Usage for base and api

### PR DESCRIPTION
**Pull request by astikans**
Refactore pretender gem to use it in `ApplicationController` and `ApiController`

### CODE REVIEW

**Comment by brunowego** [comment]
@astikans way close this?

**Comment by astikans** [comment]
@brunowego it was while ago and as I remember I should implement that impersonation works with API (`class ApiController < ActionController::API`).

But it looks that it works and no future changes were not made from me. Are you interested in new PR with these changes?

**Comment by brunowego** [comment]
@astikans thanks for the quick response. Yes, but we'll wait for @ankane to know if it's going to be approved.

**Comment by astikans** [comment]
@brunowego lets see if tests will pass and I will also test it manually in project.
Here is new PR: https://github.com/ankane/pretender/pull/13/

**Pull request closed without merging**
