### PR TITLE
reassign the impersonated_method's helper_method to make the newly cr…

### PR DESCRIPTION
**Pull request by hoenth**
…eated method available in views. 

By adding the additional helper_method assignment, current_#{:scope} returns the impersonated user in both the controller and the views

### CODE REVIEW

**Comment by ankane** [comment]
Hey @hoenth, thanks for the PR 👍  and sorry it's taken a while to get back. I'm unable to reproduce the issue. What authentication framework are you using?

**Comment by hoenth** [comment]
Hi @ankane, we use Devise. In our code, the controller version of current_admin would use the impersonated user, but the view's current_admin returned the original user. Adding the helper_method statement corrected this.

**Comment by ankane** [comment]
What versions of Rails and Devise are you on?

**Comment by hoenth** [comment]
Rails 4.2.8 and Devise 3.5.1

**Comment by ankane** [comment]
I think its something specific to your app, as I can't reproduce with either those versions or later versions.

**Comment by hoenth** [comment]
OK, i'll check again. Sorry to have bothered you with this.

**Pull request closed without merging**
